# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11c09c49fc7f20cade120f3fd10f0aaccb0223fa7b73f84561ab81dbd25aae42740318d9ee6f1537434343c8759cf0ec5582dec0a3a26c0e233b3ad5e6b4d7b6

test:
  secret_key_base: 7153ff103fb68b0ca69306034ac234bbecda2b19e83476e0718db930d5b865e24048477969be468cfc9ddd54ed9a4f767c79b49cd1af00b273133a86acdc66f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
